services:
  redis-node-1:
    image: redis:7.2.3
    command: ["/tmp/redis.sh", "192.168.1.127", "7001"]
    volumes:
      - ./redis.sh:/tmp/redis.sh
  redis-node-2:
    image: redis:7.2.3
    command: ["/tmp/redis.sh", "192.168.1.127", "7002"]
    volumes:
      - ./redis.sh:/tmp/redis.sh
  redis-node-3:
    image: redis:7.2.3
    command: ["/tmp/redis.sh", "192.168.1.127", "7003"]
    volumes:
      - ./redis.sh:/tmp/redis.sh
  redis-node-4:
    image: redis:7.2.3
    command: ["/tmp/redis.sh", "192.168.1.127", "7004"]
    volumes:
      - ./redis.sh:/tmp/redis.sh
  redis-node-5:
    image: redis:7.2.3
    command: ["/tmp/redis.sh", "192.168.1.127", "7005"]
    volumes:
      - ./redis.sh:/tmp/redis.sh
  redis-node-6:
    image: redis:7.2.3
    command: ["/tmp/redis.sh", "192.168.1.127", "7006"]
    volumes:
      - ./redis.sh:/tmp/redis.sh
  
  redis-cluster-creator:
    image: redis:7.2.3
    command: redis-cli -a 'passwd' --cluster create 192.168.1.127:7001 192.168.1.127:7002 192.168.1.127:7003 192.168.1.127:7004 192.168.1.127:7005 192.168.1.127:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-proxy
  redis-proxy:
    image: haproxytech/haproxy-alpine:2.4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8404:8404
      - 7001-7006:9001-9006
      - 7101-7106:9101-9106
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:1.14.0
    ports:
      - 8001:8001
    depends_on:
      - redis-proxy